apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: namespace-cpu-request-once
  namespace: openshift-metering
spec:
  query: namespace-cpu-request
  reportingEnd: "2020-12-30T23:59:59Z"
  reportingStart: "2020-05-01T00:00:00Z"
  runImmediately: true
