apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: operator-metering
  namespace: openshift-metering
spec:
  presto:
    spec:
      coordinator:
        resources:
          limits:
            cpu: 3.5
            memory: 5Gi
          requests:
            cpu: 2
            memory: 3Gi
    #   worker:
    #     replicas: 0
    #     resources:
    #       limits:
    #         cpu: 8
    #         memory: 8Gi
    #       requests:
    #         cpu: 4
    #         memory: 2Gi
  storage:
    hive:
      sharedPVC:
        claimName: metering-nfs
        createPVC: true
        size: 10Gi
      type: sharedPVC
    type: hive
    # uncomment the hive configuration lines, to use default values provided by the metering operators.
    # hive:
    #     spec:
    #       metastore:
    #         resources:
    #           limits:
    #             cpu: 4
    #             memory: 2Gi
    #           requests:
    #             cpu: 500m
    #             memory: 650Mi
    #         storage:
    #           class: null
    #           create: true
    #           size: 5Gi
    #       server:
    #         resources:
    #           limits:
    #             cpu: 1
    #             memory: 1Gi
    #           requests:
    #             cpu: 500m
    #             memory: 500Mi
    