apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: operator-metering
  namespace: openshift-metering
spec:
  permissions:
    meteringAdmins:
      - kind: Group
        name: metering-admins
    meteringViewers:
      - kind: Group
        name: metering-viewers
    reportExporters:
      - kind: Group
        name: cluster-admins
      - kind: User
        name: bob-from-accounting
    reporting-operator:
      spec:
        authProxy:
          htpasswd:
            data: |
              testuser:{SHA}y/2sYAj5yrQIN4TL0YdPdmGNKpc=
    reportingAdmins:
      - kind: ServiceAccount
        name: default
        namespace: my-custom-ns
    reportingViewers:
      - kind: Group
        name: reporting-readers
  presto:
    spec:
      coordinator:
        resources:
          limits:
            cpu: 3
            memory: 5Gi
          requests:
            cpu: 1.5
            memory: 3Gi
  storage:
    hive:
      sharedPVC:
        claimName: metering-nfs
        createPVC: true
        size: 10Gi
      type: sharedPVC
    type: hive
