# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
# SQL query to get pod-cpu-request in ascending order
apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: pod-cpu-request
  namespace: openshift-metering
spec:
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: varchar
    unit: kubernetes_pod
  - name: namespace
    type: varchar
    unit: kubernetes_namespace
  - name: node
    type: varchar
    unit: kubernetes_node
  - name: pod_request_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  inputs:
  - name: ReportingStart
    type: time
  - name: ReportingEnd
    type: time
  - default: pod-cpu-request-raw
    name: PodCpuRequestRawDataSourceName
    type: ReportDataSource
  query: |
  SELECT
    timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
    timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
    pod,
    namespace,
    node,
    sum(pod_request_cpu_core_seconds) as pod_request_cpu_core_seconds
  FROM {| dataSourceTableName .Report.Inputs.PodCpuRequestRawDataSourceName |}
  WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
  AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
  AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
  AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
  GROUP BY namespace, pod, node
  ORDER BY namespace, pod, node ASC, pod_request_cpu_core_seconds ASC


