apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: list-all-projects-v1
  namespace: openshift-metering
spec:
  columns:
    - name: period_start
      type: timestamp
      unit: date
    - name: period_end
      type: timestamp
      unit: date
    - name: namespace
      type: varchar
      unit: kubernetes_namespace
    - name: pod
      type: varchar
      unit: kubernetes_pod
    - name: node
      type: varchar
      unit: kubernetes_node
    - name: pod_usage_cpu_core_seconds
      type: double
      unit: cpu_core_seconds
  inputs:
    - name: ReportingStart
      type: time
    - name: ReportingEnd
      type: time
    - name: NamespaceCPUUsageReportName
      type: Report
    - default: pod-cpu-usage-raw
      name: PodCpuUsageRawDataSourceName
      type: ReportDataSource
  query: >
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
    {|- if .Report.Inputs.NamespaceCPUUsageReportName |}
      namespace,'namespace_pods',node,
      sum(pod_usage_cpu_core_seconds) as pod_usage_cpu_core_seconds
    FROM {| .Report.Inputs.NamespaceCPUUsageReportName | reportTableName |}

    WHERE period_start  >= timestamp '{| default .Report.ReportingStart
    .Report.Inputs.ReportingStart | prestoTimestamp |}'

    AND period_end <= timestamp '{| default .Report.ReportingEnd
    .Report.Inputs.ReportingEnd | prestoTimestamp |}'

    GROUP BY namespace, node

    {|- else |}
      namespace,'namespace_pods',node,
      sum(pod_usage_cpu_core_seconds) as pod_usage_cpu_core_seconds
    FROM {| dataSourceTableName .Report.Inputs.PodCpuUsageRawDataSourceName |}

    WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart
    .Report.Inputs.ReportingStart | prestoTimestamp |}'

    AND "timestamp" < timestamp '{| default .Report.ReportingEnd
    .Report.Inputs.ReportingEnd | prestoTimestamp |}'

    AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart |
    prometheusMetricPartitionFormat |}'

    AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd |
    prometheusMetricPartitionFormat |}'

    GROUP BY namespace, node

    {|- end |}
